language: ruby
rvm:
  - "2.2.2"
before_script:
  - mv config/database_travis.yml config/database.yml
  - mysql -e 'create database likejekyll'
  - bundle exec rake db:migrate
script: bundle exec rspec spec
